In [2]:
import numpy as np

3. Find the shape, size and dimension of the following array?

In [3]:
arr1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr1
print('shape-',arr1.shape)
print('size=',arr1.size)
print('dimension=',arr1.ndim)

shape- (3, 4)
size= 12
dimension= 2


 4. Write python code to access the first row of the following array?

In [4]:
arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr2
arr2[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?

In [5]:
arr2[2,3]

12

 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [6]:
arr3 = np.random.randint(0,1, size=(3,3))
arr3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

8. Describe the difference between np.random.rand and np.random.randn?

Ans-
<br>"numpy.random.rand()" generates an array of specified shapes and fills it with random values uniformly distributed between 0 and 1.
<br><br>"np.random.randn()"generates an array of shape filled with random floats sampled from a univariate “normal” distribution of mean 0 and variance 1

<br><br>  9. Write code to increase the dimension of the following array?
 <br>[[1, 2, 3, 4]
 <br>[5, 6, 7, 8],
 <br>[9, 10, 11, 12]]

In [7]:
arr3 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr3 = np.expand_dims(arr3, axis=(0))
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])


<br><br> 10. How to transpose the following array in NumPy?
 <br>[[1, 2, 3, 4]
 <br>[5, 6, 7, 8],
 <br>[9, 10, 11, 12]]



In [8]:
arr4 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr4.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

<br><br> 11. Consider the following matrix:
 <br>Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
 <br>Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [9]:
MatrixA = np.array ([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
MatrixB = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

# 1. indexwise multiplication
MatrixA * MatrixB

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [10]:
# 2. Matrix Multiplication
MatrixA = np.array ([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
MatrixB = MatrixB.reshape(4,3)


MatrixA @ MatrixB

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [11]:
#3.Add both the matrics
MatrixA = np.array ([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
MatrixB = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

MatrixA + MatrixB

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [12]:
# 4. Subtract matrix B from A
MatrixA = np.array ([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
MatrixB = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

MatrixA - MatrixB

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
# 5. Divide Matrix B by A
MatrixA = np.array ([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
MatrixB = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

MatrixB / MatrixA

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

<br><br>12.  Which function in Numpy can be used to swap the byte order of an array?


In [14]:
arr5 = np.array([1,2,3,0,6,7,8])
arr5.byteswap()

array([ 16777216,  33554432,  50331648,         0, 100663296, 117440512,
       134217728])

<br><br>13.  What is the significance of the np.linalg.inv function?


In [15]:
A = np.array([[2,3],[4,5]])

# inverse of Matrix A

print("\nInverse of A:\n", np.linalg.inv(A))


Inverse of A:
 [[-2.5  1.5]
 [ 2.  -1. ]]


<br>14. What does the np.reshape function do, and how is it used?

In [16]:
MatrixB = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

MatrixB.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])